name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
          - name: Docker-Compose Publish
            uses: pennsignals/publish_docker-compose@v0.1.1
            
